CREATE TABLE IF NOT EXISTS prices (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    dt TIMESTAMPTZ NOT NULL,
    open DOUBLE PRECISION, high DOUBLE PRECISION, low DOUBLE PRECISION, close DOUBLE PRECISION, volume DOUBLE PRECISION,
    CONSTRAINT uq_prices UNIQUE(symbol, dt)
);

CREATE TABLE IF NOT EXISTS features (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    dt TIMESTAMPTZ NOT NULL,
    rsi14 DOUBLE PRECISION, sma10 DOUBLE PRECISION, sma30 DOUBLE PRECISION, ema10 DOUBLE PRECISION,
    macd DOUBLE PRECISION, macd_signal DOUBLE PRECISION, return_1d DOUBLE PRECISION,
    CONSTRAINT uq_features UNIQUE(symbol, dt)
);

CREATE TABLE IF NOT EXISTS predictions (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    dt TIMESTAMPTZ NOT NULL,
    model TEXT NOT NULL,
    y_pred DOUBLE PRECISION,
    y_true DOUBLE PRECISION,
    CONSTRAINT uq_predictions UNIQUE(symbol, dt, model)
);

CREATE TABLE IF NOT EXISTS metrics (
    id SERIAL PRIMARY KEY,
    run_id TEXT,
    symbol TEXT NOT NULL,
    model TEXT NOT NULL,
    rmse DOUBLE PRECISION, mape DOUBLE PRECISION, directional_accuracy DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
