FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc curl git libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8000
EXPOSE 8000
ENV FLASK_APP=src.api.app:app

CMD ["gunicorn", "-b", "0.0.0.0:8000", "-w", "2", "src.api.app:app"]
